export { postPhotoService as fillingPhotoPostService } from './filling-up.service.js'
export { postNoteService as fillingNotePostService } from './filling-up.service.js'
export { patchService as fillingPatchService } from './filling-up.service.js'
export { getService as clientGetService } from './client.service.js'
export { default as adressGetService } from './adress.service.js'
